# Generated by Django 2.2 on 2020-07-30 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('Name', models.CharField(max_length=50, verbose_name='Full Name')),
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('Contact', models.IntegerField(verbose_name='Contact Number')),
                ('Address', models.CharField(max_length=400)),
            ],
        ),
    ]
